name: build-workflow

on:
  workflow_call:
    inputs:
      build:
        type: string
        required: true
      testMatrix:
        type: string
        required: true

jobs:
  build:
    name: ${{ fromJson(inputs.build).job_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Do the actual build
        run: |
          echo "Building with OS=${{fromJson(inputs.build).os}} compiler=${{fromJson(inputs.build).compiler}}"
          # e.g. cmake ... / make ...

      - name: Optional Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{fromJson(inputs.build).compiler}}-artifacts
          path: build/  # or wherever

  test:
    name: test
    needs: build
    strategy:
      matrix:
        testItem: ${{ fromJson(inputs.testMatrix) }}
    uses: ./.github/workflows/test.yml
    with:
      testItem: ${{ toJson(matrix.testItem) }}