name: test-workflow

on:
  workflow_call:
    inputs:
      testMatrix:
        type: string
        required: true
      compiler:
        type: string
        required: false  # or true if you want to use it

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testItem: ${{ fromJson(inputs.testMatrix) }}

    steps:
      - name: Check out code (or artifacts)
        uses: actions/checkout@v4

      - name: Display test details
        run: |
          echo "Compiler: ${{ inputs.compiler }}"
          echo "Test Config: ${{ matrix.testItem.config }}"
          echo "OS: ${{ matrix.testItem.os }}"
          echo "Shard: ${{ matrix.testItem.shard }}"
          # e.g. download build artifacts if needed

      - name: Actually run tests
        run: |
          echo "Now testing shard ${{ matrix.testItem.shard }} for ${{ matrix.testItem.compiler }}..."
          # e.g. python -m unittest ...
