name: test-workflow

on:
  workflow_call:
    inputs:
      testItem:
        type: string
        required: true

jobs:
  test:
    name: run-test
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.testItem.os }}
    steps:
      - name: Check out code (or artifacts)
        uses: actions/checkout@v4

      - name: Display test details
        run: |
          echo "Compiler: ${{ fromJson(inputs.testItem).compiler }}"
          echo "Test Config: ${{ fromJson(inputs.testItem).test_config }}"
          echo "OS: ${{ fromJson(inputs.testItem).os }}"
          echo "Shard: ${{ fromJson(inputs.testItem).shard }}"
          # e.g. download build artifacts if needed

      - name: Actually run tests
        run: |
          echo "Now testing shard ${{ fromJson(inputs.testItem).shard }} of ${{ fromJson(inputs.testItem).test_config }}"
          # e.g. python -m unittest ...
