name: Trigger Recursive Workflow

on:
  workflow_dispatch:
    inputs:
      initial_depth:
        description: 'Initial recursion depth'
        required: true
        default: 0
        type: number

jobs:
  start-recursion:
    runs-on: ubuntu-latest
    steps:
      - name: Start recursion test
        run: echo "Starting recursive workflow test with initial depth ${{ inputs.initial_depth }}"
  
  call-recursive:
    needs: start-recursion
    uses: izaitsevfb/recursive-workflow-prototype/.github/workflows/reusable-workflow.yml@main
    with:
      recursion_depth: ${{ inputs.initial_depth }}
